pipeline {
    agent any
    stages {
        stage("copy files to ansible-server") {
            steps {
                script {
                    echo "copying necessary files to ansible control node"
                    sshagent(['ansible-server-key']) {
                        sh "scp -o StrictHostKeyChecking=no 07-jenkins-integration/java-maven-app/ansible/* root@164.92.224.167:/root"

                        withCredentials([sshUserPrivateKey(credentialsId: 'ec2-server-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {
                            sh 'scp $keyfile root@164.92.224.167:/root/ssh-key.pem'
                        }
                    }
                }
            }
        }
    }
}