pipeline {
    agent any
    environment {
        ANSIBLE_SERVER = "164.92.224.167"
    }
    stages {
        stage("Copy files to ansible-server") {
            steps {
                script {
                    echo "copying necessary files to ansible control node"
                    sshagent(['ansible-server-key']) {
                        sh "scp -o StrictHostKeyChecking=no 07-jenkins-integration/java-maven-app/ansible/* root@${ANSIBLE_SERVER}:/root"
                        withCredentials([sshUserPrivateKey(credentialsId: 'ec2-server-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {
                            sh 'scp $keyfile root@$ANSIBLE_SERVER:/root/ssh-key.pem'
                        }
                    }
                }
            }
        }
        stage("Configure EC2 instances with ansible") {
            steps {
                script {
                    echo "calling ansible playbook to config ec2 instances"
                    def remote = [:]
                    remote.name = "ansible-server"
                    remote.host = ANSIBLE_SERVER
                    remote.allowAnyHosts = true
                    withCredentials([sshUserPrivateKey(credentialsId: 'ec2-server-key', keyFileVariable: 'keyfile', usernameVariable: 'user')]) {
                        remote.user = user
                        remote.identityFile = keyfile
                        sshScript remote: remote, script : "07-jenkins-integration/java-maven-app/prepare-ansible-server.sh"
                        sshCommand remote: remote, command: "ansible-playbook jenkins-playbook.yaml"
                    }
                }
            }
        }
    }
}